GLEWPATH = /var/lib/pacman/local/glew-2.0.0-1/
INCDIRS= -I$(GLEWPATH)/include
LIBDIRS= -L/usr/X11R6/lib -L$(GLEWPATH)/lib
LDLIBS = -lGLEW -lglut -lGLU -lGL -lX11 -lpthread -lXrandr -lXi

CPPFLAGS= $(INCDIRS) -O3 
LDFLAGS= $(CPPFLAGS) $(LIBDIRS) -Wl,-rpath,$(GLEWPATH)/lib

TARGETS = main

SRCS = main.cpp

OBJS =  $(SRCS:.cpp=.o)

CXX = g++

default: $(TARGETS)
