LIBDIRS= -L/usr/X11R6/lib
LDLIBS = -lglut -lGL -lGLU -lX11 -lm 

CPPFLAGS= -O3 
LDFLAGS= $(CPPFLAGS) $(LIBDIRS)

TARGETS = simple double

SRCS = simple.cpp double.cpp

OBJS =  $(SRCS:.cpp=.o)

CXX = g++

default: $(TARGETS)
